#!/bin/bash -eu

OUT="hotfox.xpi"
SRC="src"

build() {
  if [ -e "$OUT" ]; then
    echo >&2 "Error: Already built. Run \`clean\` first"
    echo >&2
    exit 1
  fi

  cd "$SRC"
  zip -r -FS "../$OUT" *
}

clean() {
  rm -rf "$OUT"
}
